POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "Parrots learn to make video calls to chat with other parrots",
    "author": "Schuyler Velasco",
    "url": "https://news.northeastern.edu/2023/04/21/parrots-talking-video-calls/",
    "likes": 382
}