POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFzaCIsImlkIjoiNjQ0ZTUzNmQzZDY4M2E2MDA1ZTFkYzMwIiwiaWF0IjoxNjg1MzkyNDczfQ.0xkzyw-q35E0BopRIixVbZKE3rlu4KqEllBQWH_0I6I

{
    "title": "Parrots learn to make video calls to chat with other parrots",
    "author": "Schuyler Velasco",
    "url": "https://news.northeastern.edu/2023/04/21/parrots-talking-video-calls/",
    "likes": 382
}